#!/usr/bin/env sh

# Run commitlint on the prepared commit message. Husky v9+ does not require sourcing _/husky.sh
# NOTE: --edit receives the path to the commit message file as $1 automatically
npx --no-install commitlint --edit "$1"
