name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --ci

      - name: Build
        run: npm run build

      - name: Bundle size report
        run: npm run bundle:report

      - name: Generate bundle report (file)
        if: ${{ github.event_name == 'pull_request' }}
        run: node scripts/bundle_report.mjs > bundle-report.md

      - name: Comment bundle report on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: bundle-report.md

      - name: Bundle size check (shared)
        env:
          BUNDLE_CHECK_SCOPE: shared
          BUNDLE_MAX_KB: '2400'
          BUNDLE_BASELINE_FILE: bundle-baseline.json
          BUNDLE_MAX_DELTA_KB: '60'
        run: node scripts/check_bundle_size.mjs

      - name: Bundle size check (total)
        env:
          BUNDLE_CHECK_SCOPE: total
          BUNDLE_MAX_KB: '3400'
          BUNDLE_BASELINE_FILE: bundle-baseline.json
          BUNDLE_MAX_DELTA_KB: '80'
        run: node scripts/check_bundle_size.mjs
